name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.4.0
      with:
        # API level of the platform and system image - e.g. 23 for Android Marshmallow, 29 for Android 10
        api-level: 29
        # custom script to run - e.g. `./gradlew connectedCheck`
        script: ./gradlew connectedCpptestDebugAndroidTest
    - name: Build with Gradle
      run: ./gradlew lintCppprodRelease testCppprodRelease build


