name: Android CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Lint
      run: ./gradlew lint
    - name: Unit Test
      run: ./gradlew test
    - name: Connected Android Test
      uses: ReactiveCircus/android-emulator-runner@v2.4.0
      with:
        api-level: 29
        script: |
          ./gradlew connectedAndroidTest
          chmod +x ./app/.cxx/cmake/debug/x86/cpp_test_runner.sh
          ./app/.cxx/cmake/debug/x86/cpp_test_runner.sh


