name: Publish

on:
  push:
    branches:
      - master

env:
  NDK_VERSION: 25.1.8937393
  CMAKE_VERSION: 3.22.1

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup NDK
      run: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "ndk;$NDK_VERSION" "cmake;$CMAKE_VERSION"
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build
      run: >
        ./gradlew assembleRelease
        -PversionName="$(date +"%y.%m.%d").${GITHUB_RUN_NUMBER}"
        -PversionCode=${GITHUB_RUN_NUMBER}
    - name: Sign
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ./app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Deploy
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: com.flatmapdev.synth
        releaseFile: ${{ steps.sign.outputs.signedReleaseFile }}
        track: internal
        status: completed
        mappingFile: ./app/build/outputs/mapping/release/mapping.txt


